name = "Pascal"
license = "MIT"
licenselink = "https://github.com/razonyang/hugo-theme-bootstrap/blob/master/LICENSE"
description = "Business Information here"
homepage = "https://sage-flan-e6717c.netlify.app/"
demosite = "https://sage-flan-e6717c.netlify.app/"
tags = [
  "bootstrap",
  "personal",
  "blog",
  "responsive",
  "light",
  "dark",
  "dark mode",
  "multilingual",
  "archive",
  "docs",
  "documentation"
]
features = [
  "hooks",
  "i18n",
  "comments",
  "breadcrumb",
  "search"
]
min_version = "0.84.0"
[author]
  name = "Kaz(Based on Razon Yang"
  homepage = ""
